apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-image-app
  template:
    metadata:
      labels:
        app: test-image-app
    spec:
      containers:
        - name: test-image-container
          image: test-image
