apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-service
  ports:
    - protocol: TCP
      name: server1
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: server2
      port: 3000
      targetPort: 3000
  type: NodePort
